"""initial migration

Revision ID: 444b8d0038bc
Revises: b01658fdb17b
Create Date: 2023-01-30 02:44:17.754065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444b8d0038bc'
down_revision = 'b01658fdb17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer', schema=None) as batch_op:
        batch_op.alter_column('date_added',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date_added',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date_added',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('developer', schema=None) as batch_op:
        batch_op.alter_column('date_added',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
